import type { Metadata } from "next";
import "./globals.css";
import {Footer, Navbar} from "@/app/components";

export const metadata: Metadata = {
  title: "Travel Camping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Navbar />
        <main className="relative overflow-hidden">{children}</main>
      <Footer />
      </body>
    </html>
  );
}
